### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by vlna** [ralfbecher/QlikSense_Extension_2DimHeatmap#10]
No license information at all. Please add.

**Comment by ralfbecher** [comment]
2 Dimensional Heatmap Visualization Extension for Qlik Sense is licensed under the "MIT" license:

https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/blob/master/LICENSE.md

**Comment by vlna** [comment]
Thx. Sorry for issue. I missed the license completely (I didn't was in root folder).
