### ISSUE TITLE
Change black colour if no values displayed

### ISSUE THREAD

**Issue by Aggni** [ralfbecher/QlikSense_Extension_2DimHeatmap#12]
Hello, is it possible to change the default colour of the tiles which have no data (appear as "-")? Currently they appear black which is not well received by our customer 

![image](https://user-images.githubusercontent.com/40833976/42390806-7ac85dd8-814d-11e8-84b4-64d1f03205e9.png)

**Comment by ralfbecher** [comment]
Can you give a data example?

**Comment by Aggni** [comment]
[2dimensional_heatmap_black_sample_data.xlsx](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/2257182/2dimensional_heatmap_black_sample_data.xlsx)

**Comment by Aggni** [comment]
Here it is. Many thanks for your support

**Comment by Aggni** [comment]
![image](https://user-images.githubusercontent.com/40833976/43640814-a1c14262-9721-11e8-93c3-6a2c8c40cf98.png)
 and here is how it looks like in an app with this sample data

**Comment by ralfbecher** [comment]
Now fixed.

**Comment by Aggni** [comment]
indeed - great! many thanks :-)
