### ISSUE TITLE
Issues with AVG(AGGR(COUNT(...)))

### ISSUE THREAD

**Issue by joa17890** [ralfbecher/QlikSense_Extension_2DimHeatmap#13]
I'm working with AVG(AGGR(COUNT([columnA]),columnB)).
When I pick one (X,Y), it changes the value.

**Comment by ralfbecher** [comment]
This is normal behavior, when you select you limit the data and it is recalculated. To avoid this you must exclude the dimensions from selection by set analysis like this:
AVG(AGGR(COUNT({<columnA=, columnB=>} columnA), columnB)).

**Comment by joa17890** [comment]
Thanks for the reply. But my explanation was incomplete. 
In the full table, the values ​​are not as expected.
When I select a (X, Y) it does show me the correct value.

**Comment by ralfbecher** [comment]
I think the expression makes no sense since the calculation needs to be two-dimensional. You can cross check with a table having same dimensions and measure. Else, provide a data example to verify or explain..
