### ISSUE TITLE
Conditionally color to be changes based on the expression..

### ISSUE THREAD

**Issue by kavitav25** [ralfbecher/QlikSense_Extension_2DimHeatmap#14]
Hello,

I have tried your extension... But i want to change the color based on some expression..
Is it possible to do so??
Please check the below screenshot for reference.. 
I want to built the same using the extension..
![image](https://user-images.githubusercontent.com/31730121/45620829-bb4ec900-ba9b-11e8-9030-3f73544fb41b.png)

Thanks & Regards,
Kavita

**Comment by ralfbecher** [comment]
Nice idea, but this extension will not be continued..
