### ISSUE TITLE
Cell color calculated before number on the cell

### ISSUE THREAD

**Issue by MorenoJu** [ralfbecher/QlikSense_Extension_2DimHeatmap#18]
I'm noticing that the background color of the cells are calculated before evaluating the numbers to display. If I round numbers to have only integers, 49.9 is displayed as 50, but as 49.9 < 50, the background color is yellow in my example.
How can I make the extension to evaluate what color to use after the rounding has been done?
Thanks
![image](https://user-images.githubusercontent.com/45405553/53813730-4fb6c600-3f2c-11e9-8f37-87b60710e1a8.png)

**Comment by ralfbecher** [comment]
I'm sorry, this extension is discontinued since it's now part of Qlik Visualization Bundle.
