### ISSUE TITLE
Second dimension sort incorrect when using valueloop(n1,n2)

### ISSUE THREAD

**Issue by yblake** [ralfbecher/QlikSense_Extension_2DimHeatmap#2]
When using "valueloop(0,23)" as second dimension, this result in qDimensionType[1] == 'D' (not 'N') therefore the dim2 sorting doesn't sort tiles as expected : 
![image](https://cloud.githubusercontent.com/assets/9674161/13381380/d97fc6f6-de5a-11e5-8a6c-58fcbedcf1cb.png)

**Comment by ralfbecher** [comment]
fixed
