### ISSUE TITLE
When switching between the sheets, the extension is failed to render

### ISSUE THREAD

**Issue by hemhund** [ralfbecher/QlikSense_Extension_2DimHeatmap#3]
Excellent work.
I found one issue.
When switching between the sheets, the extension is failed to render

Can you please fix it.
[Error.txt](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/213204/Error.txt)

**Comment by ralfbecher** [comment]
I cannot reproduce the issue. Could this be related to another loaded extension? Any more details? My environment is on v2.2.3

**Comment by hemhund** [comment]
I am using v2.1
I don't have any other extensions in the app.

Below are the steps to re-produce the issue.
1. Take the classBin.qvf file
2. Add a new empty sheet
3. Now traverse between the Class Binning sheet and New sheet
4. The error should appear as that Visualization Failed to Render

Not sure if it is only with me.

**Comment by ralfbecher** [comment]
Cannot reproduce on v2.2.3.
