### ISSUE TITLE
Visualisation won't render in Qlik Sense Enterprise

### ISSUE THREAD

**Issue by SarahHLamb** [ralfbecher/QlikSense_Extension_2DimHeatmap#4]
Hi there,

Great extension - this is exactly what I need.  I can create heatmaps within Qlik Sense Desktop but when I go through exactly the same process on the server the visualisation fails to render every time.

Please can you take a look into this issue for me?

Many thanks,

Sarah Lamb

**Comment by ralfbecher** [comment]
Any more details? Sense version? Console errors? I have it running on servers..

**Comment by SarahHLamb** [comment]
Hi Ralf,

We are using server version 2.0.  The error message that appears is "Error The visualization failed to render".  When I apply a calculation condition that fails, then it gives me the custom error message I set up as expected but when this condition is met then I get "Error The visualization failed to render" again.

The dimensions I am using are Date and Time.  Date is limited to 31 days (using the calculation condition) and Time is 48 half hour periods.  The measure is a sum using set analysis of consumption of a certain type.

Hope this helps?  Is there any more information you need?

Many thanks,

Sarah Lamb

**Comment by ralfbecher** [comment]
Hi Sarah,
can you send me a sample app?
Ralf

**Comment by SarahHLamb** [comment]
Hi Ralf,

Please find attached a cut down version of my app.  I've checked again and the heatmap displays fine within Qlik Sense Desktop, but when I upload it to the server then the error comes up again.

Thank you for taking the time to look into this for me,

Sarah 

[Sarah Lamb Half hourly data analysis.zip](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/259026/Sarah.Lamb.Half.hourly.data.analysis.zip)

**Comment by ralfbecher** [comment]
Please try latest (this) version. It works on my server v2.2.4 and loads up to ten data pages. However, you should limit your data (it's over 20k records) and you should use for Dim1: =Date([HH Date])

**Comment by SarahHLamb** [comment]
Hi Ralf,

Thanks for the feedback.  We'll look at upgrading our server version then.  Unfortunately we require the data granularity for other graphs but I'm using calculation conditions to limit the results shown.

Sarah
