### ISSUE TITLE
Sorting of Dimension 2 Not Working

### ISSUE THREAD

**Issue by AnalyticsEarth** [ralfbecher/QlikSense_Extension_2DimHeatmap#5]
When applying a sort to the contents of Dim 2, this is not being honoured. The sort is being applied when the same is placed on Dim 1. As soon as move back to Dim 2, this is just listed based upon a random load order.

Need to be able to specify the sort conditions for both Dim 1 and Dim 2.

When putting the same data in a Pivot table, the sorting works correctly with the same data and sort conditions.

**Comment by ralfbecher** [comment]
Sorting of Dim 2 is either numerical or text. There is no support for sorting expression since the data come in as rows ordered by Dim 1.

**Comment by ralfbecher** [comment]
Not an issue.
