### ISSUE TITLE
Visualisation won't export as pdf

### ISSUE THREAD

**Issue by SarahHLamb** [ralfbecher/QlikSense_Extension_2DimHeatmap#6]
Hi Ralf,

When I try to export a sheet as a pdf the heatmap visualisation won't load.  The error message is "Invalid visualization.  The visualization was not found on the server: bi-irregular-2dim-heatmap".  The visualisation shows fine within the app (now we've upgraded to the latest version).

Have you been able to successfully export the heatmap into a pdf document before?

Many thanks,

Sarah Lamb

**Comment by ralfbecher** [comment]
Hi Sarah,
Qlik Sense in the latest version 2.2.4 is not able to render extensions in PDF export. This might change in future versions but there is nothing I can do.
Ralf

**Comment by SarahHLamb** [comment]
Hi Ralf,

That's very disappointing but I understand there's nothing more you can do. Thank you for letting me know.

Sarah

**Comment by ralfbecher** [comment]
Let's see what 3.0 brings..

**Comment by SarahHLamb** [comment]
Hi Ralf,

I think this is now available in Qlik Sense 3.0 - see this article here: https://help.qlik.com/en-US/sense-developer/3.0/Subsystems/Extensions/Content/Howtos/extensions-enable-export.htm.

Are you able to update the extension so that this can be exported please?

Sarah

**Comment by ralfbecher** [comment]
Hi Sarah,
this should work now..
Ralf

**Comment by SarahHLamb** [comment]
Hi Ralf,

That was quick!

Thank you very much.

Sarah

**Comment by SarahHLamb** [comment]
Hi Ralf,

I'm having trouble with this exporting to pdf as it times out.  I've tried various different dpi's and page options.  Have you been able to successfully export this to pdf?  Just trying to ascertain if this is a problem with our server or not.

Thank you,

Sarah

**Comment by ralfbecher** [comment]
Hi Sarah,
this works on my side with large amount of tiles (>1400). But I think this could be more dependent on the amount of sheet objects? Can you send me a sample app?
Ralf

**Comment by ralfbecher** [comment]
Also seeing some layout issues. No idea how to improvie this.

**Comment by SarahHLamb** [comment]
Hi Ralf,

I've tried to export an app but the file size suddenly jumps from 0.16mb to 40mb when I export this from our server and I'm not sure why.  I've attached the data instead - I'm trying to show data along the side and period along the top.  Can you have a try please?

I've only got the one object on the sheet and this will never show more than 1488 tiles.

Thank you,

Sarah
[Heatmap Data Sarah Lamb.xlsx](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/461872/Heatmap.Data.Sarah.Lamb.xlsx)

**Comment by ralfbecher** [comment]
Seems to work normal on my server..
[402925aa3817427a91225c1ebabc4c68.pdf](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/462154/402925aa3817427a91225c1ebabc4c68.pdf)
[bb95aeea66874ac6a05969973fa3e5d9.pdf](https://github.com/ralfbecher/QlikSense_Extension_2DimHeatmap/files/462155/bb95aeea66874ac6a05969973fa3e5d9.pdf)

**Comment by SarahHLamb** [comment]
Hi Ralf,

Thank you for trying this.  It must be a problem with our server.

Sarah

**Comment by wdchristensen** [comment]
I have the same issue. When I use the custom addon for 2 Dimensional Heatmap and right mouse click on the visualization and select the “Export as an image” or “Export to PDF” I get an image of an error message that states “Invalid visualization The visualization was not found on the server: bi-irregular-2dim-heatmap”. The visualization can export data with no issue and all other functions within the visualization seem to work great. Will the extension export to pdf with version 3.2 and if not, what version do I need to upgrade to? Any suggestions would be greatly appreciated.

**Comment by wdchristensen** [comment]
I opened up a support case (01268145) with Qlik Support and was informed of the following:

"I tested the extension on a fresh 3.2.0 install and was able to export the data to PDF and image."

"Please let us know if you have any news, need further assistance, or if the case may be archived at this time."

The strange part is that I can restart the server (or services) and the export function will work a few times. If anyone out there knows what is happening, please comment on my question here or at my discussion on the Qlik community: 

https://community.qlik.com/thread/283897?sr=stream

**Comment by wdchristensen** [comment]
@SarahHLamb did you ever get your export working? If so, can you please share details on the solution.

**Comment by wdchristensen** [comment]
Additional testing has revealed that other add-on extensions will not export. This is not specific to the 2 dimensional heat map, I also experienced the same result with “#1 Simple KPI”.

**Comment by wdchristensen** [comment]
I noticed that if I restart the Qlik Sense Printing Service the export function will start work. I was able to download to PDF a few times and then I tried to download the Simple KPI and got the Invalid Visualization. Then the 2 Dim Heat map generated the error. I supposed I could set the service to restart every so many minutes so the issue is less obvious to users.

**Comment by SarahHLamb** [comment]
Hi

Sarah has left the company (I just get her mails forwarded to me now).  I don’t know whether she got it to work or not – it wasn’t included in the handover we did.

Regards, Stewart
