### ISSUE TITLE
Sorting by expression not working for the second dimension

### ISSUE THREAD

**Issue by pitercio** [ralfbecher/QlikSense_Extension_2DimHeatmap#7]
The first dimension of the map can be sorted by expression, but when I try to sort the second dimension, I just can do it alphabetically or numerically, the expression I write for sorting is not evaluated.

**Comment by ralfbecher** [comment]
That's true and works as designed. The sorting of the 2nd dimension is a subsorting inside the first dimension of the hypercube and doesn't work as a global sorting. What else you could do is to use the epression and create a dual value for the second dimension.
