### ISSUE TITLE
Dimension Order

### ISSUE THREAD

**Issue by JavierEscartin** [ralfbecher/QlikSense_Extension_2DimHeatmap#8]
I find this extension very useful but I have come across an issue regarding the order of the dimensions in the axes.

Let us have the following table:

`T_x:
LOAD * INLINE
[
Range_x,Range_Order_x,Weight
X,1,1
Y,2,2
Z,3,3
A,4,4
B,5,5
C,6,6
];

Outer Join (T_x)
LOAD * INLINE
[
Range_y,Range_Order_y
X2,1
Y2,2
Z2,3
A2,4
B2,5
C2,6
];

`

I want to plot a heatmap using the dimensions Range_x and Range_y, and the measure Weight (sum(Weight) actually). The order these dimensions need to be displayed is given by Range_Order_x and Range_Order_y, so these fields (actually their avg) are introduced in the sorting sections.

Unfortunately, this only seems to work for the Dimension 1 (Range_y). Dimension 2 (Range_x) seem to ignore the Sort by Expression option, and sort the values of the dimension alphabetically.

![image](https://user-images.githubusercontent.com/14348535/28308570-e63d7e58-6ba6-11e7-9750-0aa54b76f73c.png)

Note that the order of the X axis should be XYZABC according to Range_Order_X.

Thanks in advance.

**Comment by ralfbecher** [comment]
Since Range_x is the second dimension the Qlik sort expression doesn't work globally but as sub-sorting. Therefore I added my own sorting for alphabetical and numeric..
