### ISSUE TITLE
Value labels

### ISSUE THREAD

**Issue by Oritl1411** [ralfbecher/QlikSense_Extension_2DimHeatmap#9]
Hi,

I'm trying to display the values on top of the heat map instead of mouse over and don't find were and how to do this.
Any one?

Thanks 
Orit

**Comment by ralfbecher** [comment]
Go to options and switch on "Show Number in Tiles".

**Comment by Oritl1411** [comment]
Thanks for your answer but i don't have this option.
(I saw this option in the screenshots appears here  but I don't have it).

**Comment by ralfbecher** [comment]
Then download the latest.

**Comment by Oritl1411** [comment]
that's exactly what i think i did.
Can u pls send me link to the latest version or zip file with the latest version?
